// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqdkekhkwlhjdjdmakpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxZGtla2hrd2xoamRqZG1ha3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzIxMDAsImV4cCI6MjA3MDA0ODEwMH0.4HJdaYPAg59FRhp8TIvEuOBKK7ZdpCqPGwDp7_q7bDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});